### PR TITLE
Add all iOS devices

### PR DESCRIPTION
**Pull request by rekenerd**
- Group by iPod, iPhone and iPad IDs.
- Sort by device id

### CODE REVIEW

**Comment by rekenerd** [comment]
This pull request fixes https://github.com/jlippold/tweakCompatible/issues/108789

**Comment by rekenerd** [comment]
This pull request fixes https://github.com/jlippold/tweakCompatible/issues/117338

**Comment by rekenerd** [comment]
@jlippold could you please review this?

**Comment by jlippold** [comment]
Nice work, thanks man

**Review by lafi8877 — COMMENTED** [review]
L

**Pull request merged**
